from __future__ import annotations

import json
from pathlib import Path

OUT = Path(".cache/ontology/capec_primitive_behaviors.json")


def _dep(*notes: str) -> list[str]:
    """Return a list with a single deprecated marker token."""
    return ["__deprecated_" + "_".join(notes) + "__"]


# All DeepSeek manual paste batches, in order. Keep aliases verbatim.
DEEPSEEK: dict[str, list[str]] = {
    # === CAPEC 1..93 (your first 4 paste messages) ===
    "CAPEC-1": ["url_enumeration", "resource_discovery", "http_request", "parameter_injection", "authorization_bypass"],
    "CAPEC-2": ["username_enumeration", "authentication_attempt", "account_lockout"],
    "CAPEC-3": ["input_fuzzing", "parameter_injection", "path_traversal", "command_injection"],
    "CAPEC-4": ["input_fuzzing", "parameter_injection", "authorization_bypass"],
    "CAPEC-5": ["authentication_bypass", "signal_manipulation"],
    "CAPEC-6": ["parameter_injection", "command_injection", "shell_command"],
    "CAPEC-7": ["parameter_injection", "sql_injection", "sql_query_manipulation"],
    "CAPEC-8": ["buffer_overflow", "code_execution"],
    "CAPEC-9": ["buffer_overflow", "shell_command", "privilege_escalation"],
    "CAPEC-10": ["environment_variable_modification", "buffer_overflow", "code_execution"],
    "CAPEC-11": ["file_upload", "parameter_injection", "resource_discovery"],
    "CAPEC-12": ["message_identifier_manipulation", "session_impersonation"],
    "CAPEC-13": ["environment_variable_modification", "privilege_escalation"],
    "CAPEC-14": ["buffer_overflow", "code_execution"],
    "CAPEC-15": ["parameter_injection", "command_injection", "sql_injection", "shell_command"],
    "CAPEC-16": ["username_enumeration", "credential_guessing", "brute_force", "authentication_attempt"],
    "CAPEC-17": ["file_upload", "file_permission_modification", "command_execution"],
    "CAPEC-18": ["parameter_injection", "cross_site_scripting", "session_hijacking"],
    "CAPEC-19": ["parameter_injection", "cross_site_scripting", "code_execution"],
    "CAPEC-20": ["brute_force", "data_decryption_attempt"],
    "CAPEC-21": ["session_identifier_harvesting", "session_prediction", "session_impersonation"],
    "CAPEC-22": ["parameter_manipulation", "authentication_bypass"],
    "CAPEC-23": ["file_write", "file_upload", "malicious_file_execution"],
    "CAPEC-24": ["input_fuzzing", "buffer_overflow", "command_execution"],
    "CAPEC-25": ["resource_locking", "deadlock_triggering"],
    "CAPEC-26": ["file_modification", "race_condition_exploitation", "privilege_escalation"],
    "CAPEC-27": ["symlink_creation", "file_deletion", "file_write", "race_condition_exploitation"],
    "CAPEC-28": ["input_fuzzing", "parameter_injection", "command_injection", "sql_injection", "buffer_overflow"],
    "CAPEC-29": ["file_modification", "race_condition_exploitation", "privilege_escalation"],
    "CAPEC-30": ["process_memory_modification", "thread_manipulation", "code_injection", "privilege_escalation"],
    "CAPEC-31": ["http_request", "cookie_sniffing", "cookie_modification", "session_hijacking"],
    "CAPEC-32": ["url_enumeration", "parameter_injection", "cross_site_scripting", "session_hijacking"],
    "CAPEC-33": ["http_request", "http_header_manipulation", "request_smuggling"],
    "CAPEC-34": ["http_request", "http_header_injection", "response_splitting", "cross_site_scripting"],
    "CAPEC-35": ["file_modification", "configuration_manipulation", "code_execution"],
    "CAPEC-36": ["service_discovery", "authentication_bypass", "interface_enumeration", "function_discovery", "unauthorized_function_invocation"],
    "CAPEC-37": ["file_read", "data_extraction", "configuration_analysis", "reverse_engineering"],
    "CAPEC-38": ["path_modification", "command_execution"],
    "CAPEC-39": ["data_manipulation", "parameter_manipulation", "authorization_bypass"],
    "CAPEC-40": ["terminal_access", "command_injection", "shell_command"],
    "CAPEC-41": ["email_header_injection", "metacharacter_injection", "command_execution"],
    "CAPEC-42": ["buffer_overflow", "code_execution", "privilege_escalation"],
    "CAPEC-43": ["input_encoding_manipulation", "parameter_injection", "path_traversal", "command_injection", "sql_injection", "cross_site_scripting"],
    "CAPEC-44": ["file_modification", "buffer_overflow", "code_execution"],
    "CAPEC-45": ["symlink_creation", "buffer_overflow", "code_execution"],
    "CAPEC-46": ["file_modification", "parameter_injection", "buffer_overflow", "code_execution"],
    "CAPEC-47": ["parameter_injection", "buffer_overflow", "code_execution"],
    "CAPEC-48": ["local_file_access", "parameter_manipulation", "information_disclosure"],
    "CAPEC-49": ["username_enumeration", "brute_force", "authentication_attempt"],
    "CAPEC-50": ["password_recovery_exploitation", "authentication_bypass"],
    "CAPEC-51": ["registry_modification", "service_redirection", "data_manipulation"],
    "CAPEC-52": ["null_byte_injection", "path_traversal", "command_injection"],
    "CAPEC-53": ["null_byte_injection", "input_encoding_manipulation", "bypass_filter"],
    "CAPEC-54": ["parameter_probing", "error_triggering", "information_disclosure"],
    "CAPEC-55": ["hash_cracking", "password_recovery"],
    "CAPEC-56": _dep("duplicate_of_capec_207"),
    "CAPEC-57": ["network_sniffing", "credential_theft", "authentication_bypass"],
    "CAPEC-58": ["http_request", "privilege_escalation"],
    "CAPEC-59": ["session_identifier_harvesting", "session_prediction", "session_impersonation"],
    "CAPEC-60": ["session_identifier_theft", "session_replay", "session_impersonation"],
    "CAPEC-61": ["session_fixation", "session_impersonation"],
    "CAPEC-62": ["csrf_request", "session_hijacking", "privilege_escalation"],
    "CAPEC-63": ["parameter_injection", "cross_site_scripting", "session_hijacking", "code_execution"],
    "CAPEC-64": ["url_encoding_manipulation", "path_traversal", "authorization_bypass"],
    "CAPEC-65": ["network_sniffing", "code_extraction", "reverse_engineering"],
    "CAPEC-66": ["parameter_injection", "sql_injection", "sql_query_manipulation"],
    "CAPEC-67": ["format_string_injection", "buffer_overflow", "code_execution"],
    "CAPEC-68": ["code_signing_bypass", "privilege_escalation"],
    "CAPEC-69": ["process_discovery", "vulnerability_probing", "privilege_escalation", "code_execution"],
    "CAPEC-70": ["credential_guessing", "authentication_attempt"],
    "CAPEC-71": ["unicode_encoding_manipulation", "bypass_filter", "cross_site_scripting"],
    "CAPEC-72": ["url_encoding_manipulation", "parameter_injection", "path_traversal"],
    "CAPEC-73": ["file_upload", "cross_site_scripting", "redirection_manipulation"],
    "CAPEC-74": ["state_manipulation", "session_manipulation", "authorization_bypass"],
    "CAPEC-75": ["configuration_file_modification", "privilege_escalation"],
    "CAPEC-76": ["parameter_injection", "path_traversal", "file_access"],
    "CAPEC-77": ["variable_manipulation", "parameter_injection", "authorization_bypass"],
    "CAPEC-78": ["escape_character_injection", "bypass_filter", "path_traversal"],
    "CAPEC-79": ["slash_encoding_manipulation", "bypass_filter", "path_traversal"],
    "CAPEC-80": ["utf8_encoding_manipulation", "bypass_filter", "cross_site_scripting"],
    "CAPEC-81": ["log_injection", "log_tampering", "log_forging"],
    "CAPEC-82": _dep("generalization_of_capec_230_231_147"),
    "CAPEC-83": ["parameter_injection", "xpath_injection", "authentication_bypass"],
    "CAPEC-84": ["parameter_injection", "xquery_injection", "data_manipulation"],
    "CAPEC-85": ["javascript_analysis", "resource_discovery", "information_disclosure"],
    "CAPEC-86": ["http_header_injection", "cross_site_scripting", "session_hijacking"],
    "CAPEC-87": ["url_enumeration", "resource_discovery", "authorization_bypass"],
    "CAPEC-88": ["parameter_injection", "command_injection", "shell_command"],
    "CAPEC-89": ["dns_poisoning", "phishing", "credential_theft"],
    "CAPEC-90": ["authentication_protocol_exploitation", "authentication_bypass"],
    "CAPEC-91": _dep("duplicate_of_capec_18"),
    "CAPEC-92": ["integer_overflow", "buffer_overflow", "code_execution"],
    "CAPEC-93": ["log_injection", "log_tampering", "log_forging"],
    # === CAPEC 94..139 ===
    "CAPEC-94": ["network_sniffing", "man_in_the_middle", "data_manipulation"],
    "CAPEC-95": ["wsdl_scanning", "service_discovery", "information_disclosure"],
    "CAPEC-96": ["library_blocking", "error_triggering", "bypass_protection"],
    "CAPEC-97": ["cryptanalysis", "data_decryption_attempt", "information_disclosure"],
    "CAPEC-98": ["phishing", "credential_theft", "authentication_bypass"],
    "CAPEC-99": _dep("generalization_of_capec_230"),
    "CAPEC-100": ["buffer_overflow", "code_execution", "privilege_escalation"],
    "CAPEC-101": ["parameter_injection", "command_injection", "file_read"],
    "CAPEC-103": ["ui_redressing", "clickjacking", "csrf_request"],
    "CAPEC-104": ["cross_zone_scripting", "privilege_escalation", "code_execution"],
    "CAPEC-105": ["http_request", "http_header_manipulation", "request_splitting"],
    "CAPEC-106": _dep("generalization_of_capec_660_capec_699"),
    "CAPEC-107": ["http_trace_abuse", "cross_site_tracing", "session_hijacking"],
    "CAPEC-108": ["sql_injection", "command_injection", "shell_command", "code_execution"],
    "CAPEC-109": ["orm_injection", "sql_injection", "database_query_manipulation"],
    "CAPEC-110": ["soap_tampering", "sql_injection", "parameter_injection"],
    "CAPEC-111": ["json_hijacking", "data_theft", "session_hijacking"],
    "CAPEC-112": ["brute_force", "credential_guessing", "cryptanalysis"],
    "CAPEC-113": ["api_abuse", "interface_manipulation", "function_discovery"],
    "CAPEC-114": ["authentication_bypass", "privilege_escalation"],
    "CAPEC-115": ["authentication_bypass", "unauthorized_access"],
    "CAPEC-116": ["information_disclosure", "resource_discovery"],
    "CAPEC-117": ["network_sniffing", "information_disclosure"],
    "CAPEC-120": ["double_encoding", "parameter_injection", "bypass_filter"],
    "CAPEC-121": ["interface_discovery", "unauthorized_function_invocation", "privilege_escalation"],
    "CAPEC-122": ["privilege_escalation", "unauthorized_access"],
    "CAPEC-123": ["buffer_overflow", "memory_corruption", "code_execution"],
    "CAPEC-124": ["shared_resource_manipulation", "data_corruption"],
    "CAPEC-125": ["resource_flooding", "denial_of_service"],
    "CAPEC-126": ["path_traversal", "file_read", "file_write"],
    "CAPEC-127": ["directory_enumeration", "resource_discovery", "information_disclosure"],
    "CAPEC-128": ["integer_overflow", "buffer_overflow", "code_execution"],
    "CAPEC-129": ["pointer_manipulation", "memory_corruption", "code_execution"],
    "CAPEC-130": ["resource_exhaustion", "denial_of_service"],
    "CAPEC-131": ["resource_leak_exploitation", "denial_of_service"],
    "CAPEC-132": ["symlink_creation", "file_manipulation", "privilege_escalation"],
    "CAPEC-133": ["option_probing", "information_disclosure", "debug_interface_exploitation"],
    "CAPEC-134": ["email_header_injection", "command_injection"],
    "CAPEC-135": ["format_string_injection", "buffer_overflow", "code_execution"],
    "CAPEC-136": ["parameter_injection", "ldap_injection", "authentication_bypass"],
    "CAPEC-137": ["parameter_injection", "parameter_manipulation"],
    "CAPEC-138": ["reflection_injection", "code_injection", "privilege_escalation"],
    "CAPEC-139": ["path_traversal", "file_read", "file_write"],
    # === CAPEC 140..192 ===
    "CAPEC-140": ["form_bypass", "direct_url_access", "authorization_bypass"],
    "CAPEC-141": ["cache_poisoning", "data_manipulation", "redirection"],
    "CAPEC-142": ["dns_poisoning", "redirection", "pharming"],
    "CAPEC-143": ["url_enumeration", "resource_discovery", "directory_bruteforcing"],
    "CAPEC-144": ["service_discovery", "wsdl_scanning", "resource_discovery"],
    "CAPEC-145": ["checksum_spoofing", "data_manipulation", "integrity_bypass"],
    "CAPEC-146": ["xml_schema_modification", "data_manipulation", "bypass_filter"],
    "CAPEC-147": ["resource_flooding", "denial_of_service", "xml_request_flood"],
    "CAPEC-148": ["content_spoofing", "data_manipulation", "web_defacement"],
    "CAPEC-149": ["temporary_file_discovery", "information_disclosure"],
    "CAPEC-150": ["file_discovery", "resource_discovery", "information_disclosure"],
    "CAPEC-151": ["identity_spoofing", "authentication_bypass", "session_impersonation"],
    "CAPEC-153": ["input_manipulation", "parameter_injection", "data_corruption"],
    "CAPEC-154": ["resource_spoofing", "path_manipulation", "redirection"],
    "CAPEC-155": ["temporary_file_reading", "information_disclosure", "file_access"],
    "CAPEC-157": ["network_sniffing", "information_disclosure", "traffic_monitoring"],
    "CAPEC-158": ["network_sniffing", "protocol_analysis", "information_disclosure"],
    "CAPEC-159": ["library_redirection", "dll_hijacking", "code_execution"],
    "CAPEC-160": ["script_injection", "api_abuse", "command_execution"],
    "CAPEC-161": ["infrastructure_manipulation", "redirection", "pharming"],
    "CAPEC-162": ["hidden_field_manipulation", "parameter_manipulation", "data_manipulation"],
    "CAPEC-163": ["spear_phishing", "credential_theft", "social_engineering"],
    "CAPEC-164": ["mobile_phishing", "sms_spoofing", "credential_theft"],
    "CAPEC-165": ["file_manipulation", "file_attribute_modification", "data_corruption"],
    "CAPEC-166": ["system_reset", "configuration_manipulation", "bypass_protection"],
    "CAPEC-167": ["white_box_reverse_engineering", "code_analysis", "function_discovery"],
    "CAPEC-168": ["alternate_data_stream_creation", "file_hiding", "data_obfuscation"],
    "CAPEC-169": ["footprinting", "information_gathering", "resource_discovery"],
    "CAPEC-170": ["web_application_fingerprinting", "server_fingerprinting", "information_disclosure"],
    "CAPEC-171": _dep("duplicate_of_capec_77"),
    "CAPEC-173": ["action_spoofing", "ui_redressing", "clickjacking"],
    "CAPEC-174": ["flash_parameter_injection", "parameter_injection", "code_execution"],
    "CAPEC-175": ["code_inclusion", "remote_file_inclusion", "code_execution"],
    "CAPEC-176": ["configuration_manipulation", "environment_modification", "data_manipulation"],
    "CAPEC-178": ["flash_cross_site_scripting", "cross_site_flashing", "code_execution"],
    "CAPEC-179": ["micro_service_discovery", "api_enumeration", "service_probing"],
    "CAPEC-180": ["access_control_bypass", "authorization_bypass", "privilege_escalation"],
    "CAPEC-181": ["flash_overlay", "clickjacking", "ui_redressing"],
    "CAPEC-182": ["flash_injection", "parameter_injection", "code_execution"],
    "CAPEC-183": ["imap_command_injection", "smtp_command_injection", "command_injection"],
    "CAPEC-184": ["software_integrity_attack", "code_modification", "unauthorized_update"],
    "CAPEC-185": ["malware_download", "social_engineering", "file_download"],
    "CAPEC-186": ["malicious_update", "software_update_spoofing", "code_execution"],
    "CAPEC-187": ["update_redirection", "authentication_bypass", "code_execution"],
    "CAPEC-188": ["reverse_engineering", "code_analysis", "function_discovery"],
    "CAPEC-189": ["black_box_reverse_engineering", "behavioral_analysis", "function_discovery"],
    "CAPEC-190": ["executable_reverse_engineering", "code_analysis", "function_discovery"],
    "CAPEC-191": ["constant_extraction", "information_disclosure", "credential_discovery"],
    "CAPEC-192": ["protocol_analysis", "network_sniffing", "information_disclosure"],
    # === CAPEC 193..249 ===
    "CAPEC-193": ["parameter_injection", "remote_file_inclusion", "code_execution"],
    "CAPEC-194": ["identity_spoofing", "authentication_bypass", "data_manipulation"],
    "CAPEC-195": ["principal_spoofing", "identity_spoofing", "social_engineering"],
    "CAPEC-198": ["parameter_injection", "cross_site_scripting", "error_page_xss"],
    "CAPEC-200": ["filter_removal", "bypass_protection", "data_manipulation"],
    "CAPEC-201": ["xml_external_entity_injection", "file_read", "information_disclosure"],
    "CAPEC-202": ["client_application_manipulation", "api_abuse", "protocol_violation"],
    "CAPEC-203": ["registry_modification", "configuration_manipulation", "data_manipulation"],
    "CAPEC-204": ["cache_access", "information_disclosure", "data_extraction"],
    "CAPEC-205": _dep("duplicate_of_capec_37"),
    "CAPEC-206": ["code_signing", "malware_distribution", "code_execution"],
    "CAPEC-207": ["client_functionality_removal", "bypass_protection", "data_manipulation"],
    "CAPEC-208": ["client_logic_manipulation", "data_manipulation", "financial_fraud"],
    "CAPEC-209": ["file_upload", "mime_type_manipulation", "cross_site_scripting"],
    "CAPEC-211": _dep("not_legitimate"),
    "CAPEC-212": ["functionality_abuse", "privilege_escalation", "data_manipulation"],
    "CAPEC-213": _dep("duplicate_of_capec_126"),
    "CAPEC-214": _dep("merged_into_capec_215"),
    "CAPEC-215": ["input_fuzzing", "error_triggering", "information_disclosure"],
    "CAPEC-216": ["communication_channel_manipulation", "data_interception", "data_manipulation"],
    "CAPEC-217": ["ssl_tls_manipulation", "man_in_the_middle", "data_decryption"],
    "CAPEC-218": ["uddi_spoofing", "service_impersonation", "data_manipulation"],
    "CAPEC-219": ["xml_routing_manipulation", "man_in_the_middle", "data_manipulation"],
    "CAPEC-220": ["protocol_manipulation", "client_server_protocol_abuse", "data_manipulation"],
    "CAPEC-221": ["xml_external_entity_injection", "denial_of_service", "resource_exhaustion"],
    "CAPEC-222": ["iframe_overlay", "clickjacking", "csrf_request"],
    "CAPEC-224": ["fingerprinting", "information_gathering", "system_probing"],
    "CAPEC-226": ["session_credential_manipulation", "session_prediction", "session_impersonation"],
    "CAPEC-227": ["resource_tying", "denial_of_service", "resource_exhaustion"],
    "CAPEC-228": ["dtd_injection", "denial_of_service", "xml_entity_expansion"],
    "CAPEC-229": ["serialized_data_blowup", "denial_of_service", "resource_exhaustion"],
    "CAPEC-230": ["nested_payload_injection", "denial_of_service", "resource_exhaustion"],
    "CAPEC-231": ["oversized_payload_injection", "denial_of_service", "code_execution"],
    "CAPEC-233": ["privilege_escalation", "authorization_bypass", "unauthorized_access"],
    "CAPEC-234": ["process_hijacking", "privilege_escalation", "code_execution"],
    "CAPEC-235": _dep("see_capec_30"),
    "CAPEC-236": _dep("not_distinct"),
    "CAPEC-237": ["sandbox_escape", "cross_language_code_execution", "privilege_escalation"],
    "CAPEC-238": _dep("not_valid_attack"),
    "CAPEC-239": _dep("no_content"),
    "CAPEC-240": ["resource_injection", "file_modification", "data_manipulation"],
    "CAPEC-241": _dep("duplicate_of_capec_242"),
    "CAPEC-242": ["code_injection", "code_execution", "privilege_escalation"],
    "CAPEC-243": ["parameter_injection", "cross_site_scripting", "html_attribute_injection"],
    "CAPEC-244": ["uri_scheme_injection", "cross_site_scripting", "data_uri_exploitation"],
    "CAPEC-245": ["parameter_injection", "cross_site_scripting", "bypass_filter"],
    "CAPEC-246": _dep("covered_by_chaining"),
    "CAPEC-247": ["parameter_injection", "cross_site_scripting", "bypass_filter"],
    "CAPEC-248": ["command_injection", "shell_command", "code_execution"],
    "CAPEC-249": _dep("covered_by_capec_40"),
    # === CAPEC 250..444 ===
    "CAPEC-250": ["parameter_injection", "xml_injection", "authentication_bypass"],
    "CAPEC-251": ["local_file_inclusion", "file_read", "code_execution"],
    "CAPEC-252": ["local_file_inclusion", "path_traversal", "file_read"],
    "CAPEC-253": ["remote_file_inclusion", "code_execution", "file_download"],
    "CAPEC-254": _dep("legacy"),
    "CAPEC-256": ["soap_array_overflow", "buffer_overflow", "code_execution"],
    "CAPEC-257": _dep("legacy"),
    "CAPEC-258": _dep("legacy"),
    "CAPEC-259": _dep("legacy"),
    "CAPEC-260": _dep("legacy"),
    "CAPEC-261": ["input_fuzzing", "information_disclosure", "parameter_probing"],
    "CAPEC-263": ["file_corruption", "denial_of_service", "bypass_protection"],
    "CAPEC-264": _dep("legacy"),
    "CAPEC-265": _dep("legacy"),
    "CAPEC-266": _dep("legacy"),
    "CAPEC-267": ["alternate_encoding_manipulation", "bypass_filter", "command_injection"],
    "CAPEC-268": ["log_tampering", "log_forging", "log_deletion"],
    "CAPEC-269": _dep("legacy"),
    "CAPEC-270": ["registry_modification", "persistence_establishment", "code_execution"],
    "CAPEC-271": ["schema_poisoning", "data_manipulation", "bypass_filter"],
    "CAPEC-272": ["protocol_manipulation", "data_manipulation", "authentication_bypass"],
    "CAPEC-273": ["http_response_smuggling", "http_header_manipulation", "data_manipulation"],
    "CAPEC-274": ["http_verb_tampering", "authorization_bypass", "http_request"],
    "CAPEC-275": ["dns_rebinding", "bypass_same_origin_policy", "information_disclosure"],
    "CAPEC-276": ["intercomponent_protocol_manipulation", "data_manipulation", "authentication_bypass"],
    "CAPEC-277": ["data_interchange_protocol_manipulation", "data_manipulation", "authentication_bypass"],
    "CAPEC-278": ["web_services_protocol_manipulation", "parameter_manipulation", "function_abuse"],
    "CAPEC-279": ["soap_manipulation", "xml_injection", "buffer_overflow"],
    "CAPEC-280": _dep("legacy"),
    "CAPEC-285": ["icmp_ping", "host_discovery", "network_probing"],
    "CAPEC-287": ["tcp_syn_scan", "port_scanning", "network_enumeration"],
    "CAPEC-288": _dep("legacy"),
    "CAPEC-289": _dep("legacy"),
    "CAPEC-290": ["dns_mx_enumeration", "information_gathering", "network_probing"],
    "CAPEC-291": ["dns_zone_transfer", "information_disclosure", "network_mapping"],
    "CAPEC-292": ["host_discovery", "network_probing", "ping_sweep"],
    "CAPEC-293": ["traceroute", "network_mapping", "route_enumeration"],
    "CAPEC-299": ["tcp_syn_ping", "host_discovery", "network_probing"],
    "CAPEC-300": ["port_scanning", "network_enumeration", "service_discovery"],
    "CAPEC-301": ["tcp_connect_scan", "port_scanning", "network_enumeration"],
    "CAPEC-302": ["tcp_fin_scan", "port_scanning", "network_enumeration"],
    "CAPEC-303": ["tcp_xmas_scan", "port_scanning", "network_enumeration"],
    "CAPEC-304": ["tcp_null_scan", "port_scanning", "network_enumeration"],
    "CAPEC-305": ["tcp_ack_scan", "firewall_detection", "network_enumeration"],
    "CAPEC-306": ["tcp_window_scan", "os_fingerprinting", "port_scanning"],
    "CAPEC-307": ["tcp_rpc_scan", "service_discovery", "network_enumeration"],
    "CAPEC-308": ["udp_scan", "port_scanning", "network_enumeration"],
    "CAPEC-309": ["network_topology_mapping", "network_enumeration", "information_disclosure"],
    "CAPEC-310": ["vulnerability_scanning", "service_fingerprinting", "information_disclosure"],
    "CAPEC-311": _dep("legacy"),
    "CAPEC-312": ["active_os_fingerprinting", "system_probing", "information_disclosure"],
    "CAPEC-313": ["passive_os_fingerprinting", "traffic_monitoring", "information_disclosure"],
    "CAPEC-314": _dep("legacy"),
    "CAPEC-315": _dep("legacy"),
    "CAPEC-316": _dep("legacy"),
    "CAPEC-317": ["ip_id_sequencing_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-318": ["ip_id_echoed_byte_order_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-319": ["ip_df_bit_echoing_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-320": ["tcp_timestamp_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-321": ["tcp_sequence_number_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-322": ["tcp_isn_gcd_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-323": ["tcp_isn_counter_rate_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-324": ["tcp_isn_predictability_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-325": ["tcp_ecn_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-326": ["tcp_initial_window_size_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-327": ["tcp_options_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-328": ["tcp_rst_checksum_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-329": ["icmp_error_quoting_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-330": ["icmp_error_integrity_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-331": ["icmp_ip_total_length_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-332": ["icmp_ip_id_field_probe", "os_fingerprinting", "network_probing"],
    "CAPEC-383": ["api_monitoring", "information_gathering", "data_harvesting"],
    "CAPEC-384": ["api_message_manipulation", "man_in_the_middle", "data_manipulation"],
    "CAPEC-385": ["api_transaction_tampering", "data_manipulation", "financial_fraud"],
    "CAPEC-386": ["api_navigation_remapping", "redirection", "phishing"],
    "CAPEC-387": ["navigation_remapping", "malicious_content_propagation", "redirection"],
    "CAPEC-388": ["api_button_hijacking", "ui_redressing", "redirection"],
    "CAPEC-389": ["api_content_spoofing", "data_manipulation", "phishing"],
    "CAPEC-390": ["physical_security_bypass", "unauthorized_physical_access"],
    "CAPEC-391": ["physical_lock_bypass", "unauthorized_physical_access"],
    "CAPEC-392": ["lock_bumping", "physical_lock_bypass", "unauthorized_physical_access"],
    "CAPEC-393": ["lock_picking", "physical_lock_bypass", "unauthorized_physical_access"],
    "CAPEC-394": ["snap_gun_attack", "physical_lock_bypass", "unauthorized_physical_access"],
    "CAPEC-395": ["electronic_lock_bypass", "access_control_bypass", "unauthorized_physical_access"],
    "CAPEC-396": _dep("legacy"),
    "CAPEC-397": ["magnetic_strip_cloning", "access_control_bypass", "identity_spoofing"],
    "CAPEC-398": ["magnetic_strip_brute_force", "access_control_bypass", "identity_spoofing"],
    "CAPEC-399": ["rfid_cloning", "access_control_bypass", "identity_spoofing"],
    "CAPEC-400": ["rfid_deactivation", "access_control_bypass", "physical_tampering"],
    "CAPEC-401": ["hardware_tampering", "physical_access", "system_compromise"],
    "CAPEC-402": ["ata_password_bypass", "hardware_tampering", "data_access"],
    "CAPEC-404": _dep("legacy"),
    "CAPEC-405": _dep("legacy"),
    "CAPEC-406": ["dumpster_diving", "information_gathering", "physical_reconnaissance"],
    "CAPEC-407": ["pretexting", "social_engineering", "information_gathering"],
    "CAPEC-408": _dep("legacy"),
    "CAPEC-409": _dep("legacy"),
    "CAPEC-410": ["information_elicitation", "social_engineering", "information_gathering"],
    "CAPEC-411": _dep("legacy"),
    "CAPEC-412": ["pretexting_customer_service", "social_engineering", "information_gathering"],
    "CAPEC-413": ["pretexting_tech_support", "social_engineering", "information_gathering"],
    "CAPEC-414": ["pretexting_delivery", "social_engineering", "physical_access"],
    "CAPEC-415": ["pretexting_phone", "social_engineering", "information_gathering"],
    "CAPEC-416": ["human_behavior_manipulation", "social_engineering", "information_gathering"],
    "CAPEC-417": ["perception_influence", "social_engineering", "information_gathering"],
    "CAPEC-418": ["reciprocation_influence", "social_engineering", "information_gathering"],
    "CAPEC-419": _dep("legacy"),
    "CAPEC-420": ["scarcity_influence", "social_engineering", "information_gathering"],
    "CAPEC-421": ["authority_influence", "social_engineering", "information_gathering"],
    "CAPEC-422": ["commitment_consistency_influence", "social_engineering", "information_gathering"],
    "CAPEC-423": ["liking_influence", "social_engineering", "information_gathering"],
    "CAPEC-424": ["consensus_social_proof_influence", "social_engineering", "information_gathering"],
    "CAPEC-425": ["framing_influence", "social_engineering", "information_gathering"],
    "CAPEC-426": ["incentive_influence", "social_engineering", "information_gathering"],
    "CAPEC-427": ["psychological_influence", "social_engineering", "information_gathering"],
    "CAPEC-428": ["mode_of_thinking_influence", "social_engineering", "information_gathering"],
    "CAPEC-429": ["eye_cue_influence", "social_engineering", "information_gathering"],
    "CAPEC-430": _dep("legacy"),
    "CAPEC-431": _dep("legacy"),
    "CAPEC-432": _dep("legacy"),
    "CAPEC-433": ["human_buffer_overflow", "social_engineering", "subconscious_influence"],
    "CAPEC-434": ["interview_interrogation_influence", "social_engineering", "information_gathering"],
    "CAPEC-435": ["instant_rapport_influence", "social_engineering", "information_gathering"],
    "CAPEC-438": ["manufacturing_modification", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-439": ["distribution_manipulation", "supply_chain_attack", "product_tampering"],
    "CAPEC-440": ["hardware_integrity_attack", "physical_access", "hardware_tampering"],
    "CAPEC-441": ["malware_insertion", "system_compromise", "code_execution"],
    "CAPEC-442": ["infected_software", "malware_distribution", "code_execution"],
    "CAPEC-443": ["insider_malicious_logic_insertion", "supply_chain_attack", "code_execution"],
    "CAPEC-444": ["development_alteration", "supply_chain_attack", "code_execution"],
    # === CAPEC 445..539 ===
    "CAPEC-445": ["configuration_management_manipulation", "malicious_code_insertion", "supply_chain_attack"],
    "CAPEC-446": ["third_party_component_injection", "malicious_code_insertion", "supply_chain_attack"],
    "CAPEC-447": ["design_alteration", "system_weakening", "supply_chain_attack"],
    "CAPEC-448": ["dll_infection", "malware_insertion", "code_execution"],
    "CAPEC-449": _dep("legacy"),
    "CAPEC-450": _dep("legacy"),
    "CAPEC-451": _dep("legacy"),
    "CAPEC-452": ["hardware_infection", "malware_insertion", "system_compromise"],
    "CAPEC-453": _dep("legacy"),
    "CAPEC-454": _dep("legacy"),
    "CAPEC-455": _dep("legacy"),
    "CAPEC-456": ["memory_infection", "malware_insertion", "system_compromise"],
    "CAPEC-457": ["usb_malware_insertion", "malware_execution", "system_compromise"],
    "CAPEC-458": ["flash_memory_infection", "malware_insertion", "bios_compromise"],
    "CAPEC-459": ["certificate_forgery", "hash_collision_exploitation", "authority_spoofing"],
    "CAPEC-460": ["http_parameter_pollution", "parameter_manipulation", "bypass_filter"],
    "CAPEC-461": ["hash_extension_attack", "signature_forgery", "api_authentication_bypass"],
    "CAPEC-462": ["cross_domain_timing_attack", "information_disclosure", "side_channel_attack"],
    "CAPEC-463": ["padding_oracle_attack", "data_decryption", "cryptanalysis"],
    "CAPEC-464": ["persistent_cookie_creation", "cookie_resurrection", "user_tracking"],
    "CAPEC-465": ["transparent_proxy_abuse", "man_in_the_middle", "data_interception"],
    "CAPEC-466": ["active_man_in_the_middle", "same_origin_policy_bypass", "data_interception"],
    "CAPEC-467": ["cross_site_identification", "information_gathering", "social_media_profiling"],
    "CAPEC-468": ["css_injection", "cross_domain_theft", "information_disclosure"],
    "CAPEC-469": ["http_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-470": ["sql_injection", "operating_system_compromise", "privilege_escalation"],
    "CAPEC-471": ["search_order_hijacking", "dll_hijacking", "code_execution"],
    "CAPEC-472": ["browser_fingerprinting", "information_gathering", "system_profiling"],
    "CAPEC-473": ["signature_spoofing", "authentication_bypass", "authority_spoofing"],
    "CAPEC-474": ["private_key_theft", "signature_forgery", "authority_impersonation"],
    "CAPEC-475": ["signature_verification_bypass", "authentication_bypass", "cryptographic_weakness_exploitation"],
    "CAPEC-476": ["signature_display_manipulation", "identity_spoofing", "homograph_attack"],
    "CAPEC-477": ["signed_unsigned_mix_manipulation", "integrity_bypass", "data_manipulation"],
    "CAPEC-478": ["windows_service_configuration_modification", "persistence_establishment", "code_execution"],
    "CAPEC-479": ["malicious_root_certificate_installation", "certificate_trust_abuse", "man_in_the_middle"],
    "CAPEC-480": ["virtualization_escape", "privilege_escalation", "code_execution"],
    "CAPEC-481": ["domain_fronting", "traffic_routing_manipulation", "c2_obfuscation"],
    "CAPEC-482": ["tcp_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-484": _dep("legacy"),
    "CAPEC-485": ["private_key_recovery", "signature_forgery", "cryptanalysis"],
    "CAPEC-486": ["udp_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-487": ["icmp_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-488": ["http_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-489": ["ssl_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-490": ["amplification_attack", "denial_of_service", "resource_exhaustion"],
    "CAPEC-491": ["quadratic_data_expansion", "denial_of_service", "resource_exhaustion"],
    "CAPEC-492": ["regex_exponential_blowup", "denial_of_service", "resource_exhaustion"],
    "CAPEC-493": ["soap_array_blowup", "denial_of_service", "resource_exhaustion"],
    "CAPEC-494": ["tcp_fragmentation", "firewall_evasion", "packet_manipulation"],
    "CAPEC-495": ["udp_fragmentation", "denial_of_service", "resource_exhaustion"],
    "CAPEC-496": ["icmp_fragmentation", "denial_of_service", "resource_exhaustion"],
    "CAPEC-497": ["file_discovery", "information_gathering", "resource_enumeration"],
    "CAPEC-498": ["ios_screenshot_probing", "information_disclosure", "data_extraction"],
    "CAPEC-499": ["android_intent_interception", "information_disclosure", "data_manipulation"],
    "CAPEC-500": ["webview_injection", "cross_site_scripting", "information_disclosure"],
    "CAPEC-501": ["android_activity_hijacking", "ui_spoofing", "credential_theft"],
    "CAPEC-502": ["intent_spoofing", "api_abuse", "unauthorized_action"],
    "CAPEC-503": ["webview_exposure", "api_abuse", "unauthorized_access"],
    "CAPEC-504": ["task_impersonation", "ui_spoofing", "privilege_escalation"],
    "CAPEC-505": ["scheme_squatting", "url_scheme_abuse", "credential_theft"],
    "CAPEC-506": ["tapjacking", "ui_redressing", "clickjacking"],
    "CAPEC-507": ["physical_theft", "hardware_access", "data_extraction"],
    "CAPEC-508": ["shoulder_surfing", "information_gathering", "credential_theft"],
    "CAPEC-509": ["kerberoasting", "credential_harvesting", "privilege_escalation"],
    "CAPEC-510": ["saas_request_forgery", "session_hijacking", "unauthorized_action"],
    "CAPEC-511": ["ide_infiltration", "malware_insertion", "supply_chain_attack"],
    "CAPEC-516": ["hardware_component_substitution_baselining", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-517": ["documentation_alteration_circumvent_dialdown", "supply_chain_attack", "information_manipulation"],
    "CAPEC-518": ["documentation_alteration_underperforming", "supply_chain_attack", "system_weakening"],
    "CAPEC-519": ["documentation_alteration_design_error", "supply_chain_attack", "system_weakening"],
    "CAPEC-520": ["counterfeit_hardware_insertion_assembly", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-521": ["hardware_design_specification_alteration", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-522": ["malicious_hardware_component_replacement", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-523": ["malicious_software_implantation", "supply_chain_attack", "malware_insertion"],
    "CAPEC-524": ["rogue_integration_procedures", "supply_chain_attack", "malware_insertion"],
    "CAPEC-528": ["xml_flood", "denial_of_service", "resource_exhaustion"],
    "CAPEC-529": ["malware_directed_reconnaissance", "information_gathering", "network_probing"],
    "CAPEC-530": ["counterfeit_component_provision", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-534": ["malicious_hardware_update", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-535": ["malicious_gray_market_hardware", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-536": ["configuration_data_injection", "system_weakening", "data_manipulation"],
    "CAPEC-537": ["hardware_development_environment_infiltration", "supply_chain_attack", "hardware_tampering"],
    "CAPEC-538": ["open_source_library_manipulation", "supply_chain_attack", "malicious_code_insertion"],
    "CAPEC-539": ["asic_malicious_functionality", "supply_chain_attack", "hardware_tampering"],
    # === CAPEC 540..624 ===
    "CAPEC-540": ["buffer_overread", "information_disclosure", "memory_read"],
    "CAPEC-541": ["application_fingerprinting", "information_gathering", "system_profiling"],
    "CAPEC-543": ["counterfeit_website_creation", "phishing", "malware_distribution"],
    "CAPEC-544": ["counterfeit_organization_creation", "supply_chain_attack", "malware_insertion"],
    "CAPEC-545": ["system_resource_probing", "information_disclosure", "data_extraction"],
    "CAPEC-547": ["physical_destruction", "hardware_damage", "denial_of_service"],
    "CAPEC-548": ["resource_contamination", "denial_of_service", "information_disclosure"],
    "CAPEC-549": ["local_code_execution", "malware_installation", "system_compromise"],
    "CAPEC-550": ["new_service_installation", "persistence_establishment", "privilege_escalation"],
    "CAPEC-551": ["existing_service_modification", "persistence_establishment", "code_execution"],
    "CAPEC-552": ["rootkit_installation", "system_hiding", "persistence_establishment"],
    "CAPEC-554": ["functionality_bypass", "protection_mechanism_disable", "unauthorized_access"],
    "CAPEC-555": ["remote_service_access", "credential_use", "unauthorized_access"],
    "CAPEC-556": ["file_extension_handler_modification", "code_execution", "persistence_establishment"],
    "CAPEC-557": _dep("legacy"),
    "CAPEC-558": ["trusted_executable_replacement", "code_execution", "persistence_establishment"],
    "CAPEC-559": ["orbital_jamming", "satellite_communication_disruption", "denial_of_service"],
    "CAPEC-560": ["known_credential_use", "authentication_attempt", "unauthorized_access"],
    "CAPEC-561": ["windows_admin_share_access", "credential_use", "remote_file_access"],
    "CAPEC-562": ["shared_file_modification", "malware_insertion", "code_execution"],
    "CAPEC-563": ["malicious_file_upload_webroot", "code_execution", "webshell_deployment"],
    "CAPEC-564": ["logon_script_modification", "persistence_establishment", "code_execution"],
    "CAPEC-565": ["password_spraying", "credential_guessing", "authentication_attempt"],
    "CAPEC-566": _dep("legacy"),
    "CAPEC-567": _dep("legacy"),
    "CAPEC-568": ["keylogger_deployment", "credential_capture", "information_disclosure"],
    "CAPEC-569": ["user_data_collection", "credential_capture", "information_disclosure"],
    "CAPEC-570": _dep("legacy"),
    "CAPEC-571": ["logging_block", "hide_activities", "forensic_obstruction"],
    "CAPEC-572": ["file_size_inflation", "denial_of_service", "data_corruption"],
    "CAPEC-573": ["process_enumeration", "information_gathering", "system_profiling"],
    "CAPEC-574": ["service_enumeration", "information_gathering", "system_profiling"],
    "CAPEC-575": ["account_enumeration", "information_gathering", "system_profiling"],
    "CAPEC-576": ["group_permission_enumeration", "information_gathering", "system_profiling"],
    "CAPEC-577": ["owner_enumeration", "information_gathering", "system_profiling"],
    "CAPEC-578": ["security_software_disable", "hide_activities", "bypass_protection"],
    "CAPEC-579": ["winlogon_dll_replacement", "persistence_establishment", "code_execution"],
    "CAPEC-580": ["system_footprinting", "information_gathering", "system_profiling"],
    "CAPEC-581": ["security_software_footprinting", "information_gathering", "system_profiling"],
    "CAPEC-582": ["route_disabling", "denial_of_service", "network_disruption"],
    "CAPEC-583": ["network_hardware_disable", "denial_of_service", "physical_attack"],
    "CAPEC-584": ["bgp_route_disabling", "denial_of_service", "network_disruption"],
    "CAPEC-585": ["dns_domain_seizure", "denial_of_service", "domain_takeover"],
    "CAPEC-586": ["object_injection", "deserialization_exploitation", "code_execution"],
    "CAPEC-587": ["cross_frame_scripting", "information_disclosure", "session_hijacking"],
    "CAPEC-588": ["dom_based_xss", "cross_site_scripting", "session_hijacking"],
    "CAPEC-589": ["dns_blocking", "denial_of_service", "network_filtering"],
    "CAPEC-590": ["ip_blocking", "denial_of_service", "network_filtering"],
    "CAPEC-591": ["reflected_xss", "cross_site_scripting", "session_hijacking"],
    "CAPEC-592": ["stored_xss", "cross_site_scripting", "persistent_xss"],
    "CAPEC-593": ["session_hijacking", "session_impersonation", "unauthorized_access"],
    "CAPEC-594": ["traffic_injection", "data_manipulation", "denial_of_service"],
    "CAPEC-595": ["connection_reset", "denial_of_service", "network_disruption"],
    "CAPEC-596": ["tcp_rst_injection", "connection_termination", "denial_of_service"],
    "CAPEC-597": ["absolute_path_traversal", "file_read", "file_write"],
    "CAPEC-598": ["dns_spoofing", "redirection", "man_in_the_middle"],
    "CAPEC-599": ["terrestrial_jamming", "satellite_disruption", "denial_of_service"],
    "CAPEC-600": ["credential_stuffing", "authentication_attempt", "unauthorized_access"],
    "CAPEC-601": ["jamming", "denial_of_service", "communication_disruption"],
    "CAPEC-602": _dep("legacy"),
    "CAPEC-603": ["resource_blockage", "denial_of_service", "system_disruption"],
    "CAPEC-604": ["wifi_jamming", "denial_of_service", "network_disruption"],
    "CAPEC-605": ["cellular_jamming", "denial_of_service", "communication_disruption"],
    "CAPEC-606": ["cellular_encryption_weakening", "encryption_bypass", "information_disclosure"],
    "CAPEC-607": ["obstruction", "denial_of_service", "system_disruption"],
    "CAPEC-608": ["cellular_encryption_cryptanalysis", "data_decryption", "information_disclosure"],
    "CAPEC-609": ["cellular_traffic_intercept", "information_disclosure", "data_capture"],
    "CAPEC-610": ["cellular_data_injection", "data_manipulation", "denial_of_service"],
    "CAPEC-611": ["bitsquatting", "domain_impersonation", "redirection"],
    "CAPEC-612": ["wifi_mac_tracking", "user_tracking", "location_tracking"],
    "CAPEC-613": ["wifi_ssid_tracking", "user_tracking", "location_tracking"],
    "CAPEC-614": ["sim_rooting", "ota_exploitation", "code_execution"],
    "CAPEC-615": ["evil_twin_attack", "man_in_the_middle", "information_disclosure"],
    "CAPEC-616": ["rogue_location_establishment", "resource_spoofing", "redirection"],
    "CAPEC-617": ["cellular_rogue_base_station", "man_in_the_middle", "information_disclosure"],
    "CAPEC-618": ["cellular_broadcast_request", "location_tracking", "information_disclosure"],
    "CAPEC-619": ["signal_strength_tracking", "location_tracking", "user_tracking"],
    "CAPEC-621": ["packet_timing_analysis", "information_disclosure", "side_channel_attack"],
    "CAPEC-622": ["electromagnetic_side_channel", "cryptographic_key_recovery", "information_disclosure"],
    "CAPEC-624": ["hardware_fault_injection", "cryptographic_key_recovery", "bypass_protection"],
    # === CAPEC 625..674 ===
    "CAPEC-625": ["mobile_device_fault_injection", "cryptographic_key_recovery", "side_channel_attack"],
    "CAPEC-626": ["smudge_attack", "password_discovery", "physical_access"],
    "CAPEC-627": ["gps_spoofing", "counterfeit_gps_signal", "location_manipulation"],
    "CAPEC-628": ["carry_off_gps_attack", "gps_spoofing", "location_manipulation"],
    "CAPEC-629": _dep("legacy"),
    "CAPEC-630": ["typosquatting", "domain_impersonation", "redirection"],
    "CAPEC-631": ["soundsquatting", "domain_impersonation", "redirection"],
    "CAPEC-632": ["homograph_attack", "domain_impersonation", "redirection"],
    "CAPEC-633": ["token_impersonation", "authentication_bypass", "privilege_escalation"],
    "CAPEC-634": ["audio_video_peripheral_probing", "information_disclosure", "surveillance"],
    "CAPEC-635": ["deceptive_filename_exploitation", "code_execution", "file_extension_manipulation"],
    "CAPEC-636": ["malicious_data_hiding", "alternate_data_stream_creation", "file_obfuscation"],
    "CAPEC-637": ["clipboard_data_collection", "information_disclosure", "data_exfiltration"],
    "CAPEC-638": ["component_firmware_alteration", "mbr_modification", "persistence_establishment"],
    "CAPEC-639": ["system_file_probing", "information_disclosure", "file_access"],
    "CAPEC-640": ["code_inclusion_existing_process", "dll_injection", "privilege_escalation"],
    "CAPEC-641": ["dll_side_loading", "dll_hijacking", "code_execution"],
    "CAPEC-643": ["shared_file_discovery", "information_gathering", "lateral_movement_preparation"],
    "CAPEC-644": ["pass_the_hash", "credential_hijacking", "authentication_bypass"],
    "CAPEC-645": ["pass_the_ticket", "kerberos_ticket_hijacking", "authentication_bypass"],
    "CAPEC-646": ["peripheral_footprinting", "information_gathering", "system_profiling"],
    "CAPEC-647": ["registry_data_collection", "information_disclosure", "system_profiling"],
    "CAPEC-648": ["screen_capture_data_collection", "information_disclosure", "surveillance"],
    "CAPEC-649": ["file_extension_space_manipulation", "code_execution", "file_extension_manipulation"],
    "CAPEC-650": ["webshell_upload", "remote_code_execution", "persistence_establishment"],
    "CAPEC-651": ["eavesdropping", "information_disclosure", "surveillance"],
    "CAPEC-652": ["known_kerberos_credential_use", "authentication_attempt", "unauthorized_access"],
    "CAPEC-653": ["known_os_credential_use", "authentication_attempt", "unauthorized_access"],
    "CAPEC-654": ["credential_prompt_impersonation", "ui_spoofing", "credential_theft"],
    "CAPEC-655": ["file_size_inflation", "hash_evasion", "bypass_protection"],
    "CAPEC-656": ["voice_phishing", "credential_theft", "social_engineering"],
    "CAPEC-657": ["malicious_automated_update_spoofing", "software_update_manipulation", "code_execution"],
    "CAPEC-660": ["root_detection_evasion_hooking", "bypass_protection", "privilege_escalation"],
    "CAPEC-661": ["root_detection_evasion_debugging", "bypass_protection", "privilege_escalation"],
    "CAPEC-662": ["adversary_in_browser", "man_in_the_middle", "data_manipulation"],
    "CAPEC-663": ["transient_instruction_exploitation", "side_channel_attack", "information_disclosure"],
    "CAPEC-664": ["server_side_request_forgery", "unauthorized_request", "information_disclosure"],
    "CAPEC-665": ["thunderbolt_protocol_exploitation", "firmware_manipulation", "bypass_protection"],
    "CAPEC-666": ["bluesmacking", "bluetooth_flooding", "denial_of_service"],
    "CAPEC-667": ["bluetooth_impersonation", "mac_address_spoofing", "authentication_bypass"],
    "CAPEC-668": ["knob_attack", "bluetooth_key_negotiation_exploitation", "information_disclosure"],
    "CAPEC-669": ["software_update_alteration", "malware_insertion", "code_execution"],
    "CAPEC-670": ["development_tools_malicious_alteration", "supply_chain_attack", "code_execution"],
    "CAPEC-671": ["asic_requirements_alteration", "supply_chain_attack", "design_manipulation"],
    "CAPEC-672": ["chip_programming_malicious_code", "hardware_tampering", "code_execution"],
    "CAPEC-673": ["developer_signing_malicious_software", "supply_chain_attack", "code_execution"],
    "CAPEC-674": ["fpga_design_alteration", "hardware_tampering", "logic_manipulation"],
    # === CAPEC 675..702 ===
    "CAPEC-675": ["decommissioned_device_data_retrieval", "information_disclosure", "data_extraction"],
    "CAPEC-676": ["nosql_injection", "parameter_injection", "authentication_bypass"],
    "CAPEC-677": ["server_motherboard_compromise", "firmware_manipulation", "persistence_establishment"],
    "CAPEC-678": ["system_build_data_alteration", "configuration_manipulation", "system_weakening"],
    "CAPEC-679": ["memory_protection_exploitation", "memory_corruption", "code_execution"],
    "CAPEC-680": ["register_control_exploitation", "data_manipulation", "information_disclosure"],
    "CAPEC-681": ["hardware_security_identifier_exploitation", "privilege_escalation", "access_control_bypass"],
    "CAPEC-682": ["unpatchable_firmware_exploitation", "firmware_vulnerability_abuse", "system_compromise"],
    "CAPEC-690": ["metadata_spoofing", "resource_impersonation", "integrity_bypass"],
    "CAPEC-691": ["open_source_metadata_spoofing", "software_impersonation", "code_execution"],
    "CAPEC-692": ["vcs_commit_metadata_spoofing", "repository_impersonation", "code_execution"],
    "CAPEC-693": ["starjacking", "package_popularity_spoofing", "code_execution"],
    "CAPEC-694": ["system_location_discovery", "information_gathering", "system_profiling"],
    "CAPEC-695": ["repo_jacking", "repository_hijacking", "code_execution"],
    "CAPEC-696": ["load_value_injection", "transient_execution_exploitation", "information_disclosure"],
    "CAPEC-697": ["dhcp_spoofing", "rogue_dhcp_server", "man_in_the_middle"],
    "CAPEC-698": ["malicious_extension_installation", "malware_insertion", "code_execution"],
    "CAPEC-699": ["monitor_eavesdropping", "information_disclosure", "side_channel_attack"],
    "CAPEC-700": ["network_boundary_bridging", "network_segmentation_bypass", "lateral_movement"],
    "CAPEC-701": ["browser_in_the_middle", "man_in_the_middle", "data_manipulation"],
    "CAPEC-702": ["hardware_debug_interface_exploitation", "debug_functionality_abuse", "privilege_escalation"],
}


def main() -> None:
    payload = {
        "source": ".cache\\mitre_attack\\capec_canonical.json",
        "model": "deepseek-v3-offline-manual",
        "count": len(DEEPSEEK),
        "behaviors": DEEPSEEK,
        "sources": ["deepseek-manual"],
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    real = sum(
        1 for v in DEEPSEEK.values()
        if v and not any(t.startswith("__deprecated") for t in v)
    )
    dep = len(DEEPSEEK) - real
    print(f"Wrote {OUT}")
    print(f"  total: {len(DEEPSEEK)}")
    print(f"  real: {real}")
    print(f"  deprecated: {dep}")
    print(f"  top-level keys: {list(payload.keys())}")


if __name__ == "__main__":
    main()